<%@ Page Language="C#" AutoEventWireup="true" Codebehind="TestJScript.aspx.cs" Inherits="Scripts.Classes.Documents.Test.TestJScript" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
	<title>Untitled Page</title>

	<script type="text/javascript">
	//------------------------------------------------------------------------------
	/// 
	///     This code was generated by a tool.
	///     Runtime Version: 2.0.50727.1433
	///
	///     Changes to this file may cause incorrect behavior and will be lost if 
	///     the code is regenerated.
	/// 
	//------------------------------------------------------------------------------

	//@cc_on
	//@set @debug(off)

	var i import = function(){};

	import System;

	package Samples {
	    
		public class Class1 {
	        
			public static function Main() {
				System.Console.WriteLine("Hello World!");
			}
		}
	}
	Samples.Class1.Main();
	</script>

</head>
<body>
	<form id="form1" runat="server">
		<div>
		</div>
	</form>
</body>
</html>
